import os

pluginName = 'cyclone.bundle'

HOME = os.environ['HOME']

# Paths for Maya on Mac OSX
MAYA_PATH = '/Applications/Autodesk/maya2012'
MAYA_INCLUDE_PATH = MAYA_PATH+'/devkit/include/'
MAYA_LIB_PATH = MAYA_PATH+'/Maya.app/Contents/MacOS'
MAYA_PLUG_IN_INSTALL_PATH = HOME+'/Library/Preferences/Autodesk/maya/2012-x64/plug-ins'

env = Environment()
env.Append(CCFLAGS = ['-I'+MAYA_INCLUDE_PATH, '-includemaya/OpenMayaMac.h'])
env.Append(CCFLAGS = ['-DMAC_PLUGIN', '-D_BOOL', '-DREQUIRE_IOSTREAM'])
env.Append(LIBS = ['OpenMaya','Foundation','OpenMayaFX','OpenMayaUI'])
env.Append(LIBPATH = [MAYA_LIB_PATH])

env.SharedLibrary(pluginName, Glob('*.cpp'), SHLIBPREFIX='')

install_plugin = env.Install(MAYA_PLUG_IN_INSTALL_PATH, pluginName)
env.Alias('install', [install_plugin])

